version: '3.3'
services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_DB=carangobom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

# Names our volume
volumes:
  my-db: