spring:
    datasource:
        driverClassName: org.postgresql.Driver
        hikari:
            max-lifetime: 600000
        password: postgres
        url: jdbc:postgresql://localhost:5432/carangobom
        username: postgres
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

carango-bom-api:
    cors:
        allow-credential: true
        allowed:
            origin: http://localhost:3000
            methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, TRACE, CONNECT
    jwt:
        expiration: 86400000
        secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN}x3?JR3.2zr~v)gYF^8:8>:XfB:Ww75N/emt9Yj[bQMNCWwWJ?N,nvH.<2.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
server:
    port: ${PORT:8080}

---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        driverClassName: org.postgresql.Driver
        hikari:
            max-lifetime: 600000
        password: postgres
        url: jdbc:postgresql://localhost:5432/it
        username: postgres

---
spring:
    profiles: prod
server:
    error:
        include-stacktrace: on_trace_param