version: '3.3'
services:
  api:
    build:
      context: ../.devcontainer
      dockerfile: Dockerfile
      args:
        - VARIANT=11
        - INSTALL_MAVEN=true
        - INSTALL_GRADLE=false
        - INSTALL_NODE=false
        - NODE_VERSION=lts/*
    ports:
      - 8080:8080
    volumes:
      - ..:/workspaces/carango-bom-api
    environment:
      MYSQL_HOST: db
    # https://code.visualstudio.com/docs/remote/create-dev-container#_extend-your-docker-compose-file-for-development
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
